version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo "Installing Python 3"
      - sudo apt update -y
      - sudo apt install -y python3
artifacts:
  files:
    - '**/*'
