version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - sudo apt update -y
      - sudo apt install -y python3
      - wget terraform.zip https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      - unzip terraform_1.7.4_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - rm -rf terraform.zip
      

  build:
    commands:
      - echo "Installing Python 3"     
artifacts:
  files:
    - '**/*'