version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - sudo apt update -y
      - sudo apt install -y python3
      - wget https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      - unzip terraform_1.7.4_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - rm -rf terraform.zip
      - wget -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo npm install -g typescript@5.1.6
      - sudo apt install ansible -y
      - sudo apt-get install -y jq

      - wget https://github.com/eksctl-io/eksctl/releases/download/v0.171.0/eksctl_Linux_amd64.tar.gz
      - tar -xvf eksctl_Linux_amd64.tar.gz
      - sudo mv eksctl /usr/local/bin
       
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.15.10.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
       
  build:
    commands:
      - echo "Installing Python 3"     
artifacts:
  files:
    - '**/*'